version: "3"

services:
  db:
    build: ./db
    image: knex-pg-example-db:latest
    container_name: knex-pg-example-db
    env_file: configs/.env
    volumes:
      - knex-pg-example-db:/var/lib/postgresql/data
    ports:
    - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  knex-pg-example-db:
    driver: local